# Generated by Django 2.0.8 on 2018-08-11 21:25

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestBoolDefault",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_functional", models.BooleanField(default=False)),
            ],
        ),
        AddDefaultValue("TestBoolDefault", "is_functional", False),
    ]
