# Generated by Django 2.0.8 on 2018-08-12 16:09

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [("dadv", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="TestTextDefault",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(default="No description provided")),
            ],
        ),
        AddDefaultValue(
            model_name="TestTextDefault",
            name="description",
            value="No description provided",
        ),
    ]
