# Generated by Django 2.0.8 on 2018-08-12 17:06

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [("dadv", "0002_testtextdefault")]

    operations = [
        migrations.CreateModel(
            name="TestHappyPath",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Happy path", max_length=15)),
            ],
        ),
        AddDefaultValue(model_name="TestHappyPath", name="name", value="Happy path"),
    ]
