# Generated by Django 2.0.8 on 2018-08-12 18:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django_add_default_value import AddDefaultValue, NOW, TODAY


class Migration(migrations.Migration):

    dependencies = [("dadv", "0003_testhappypath")]

    operations = [
        migrations.AddField(
            model_name="testhappypath",
            name="dob",
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AddField(
            model_name="testhappypath",
            name="rebirth",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="testhappypath",
            name="married",
            field=models.DateField(default=datetime.date.today),
        ),
        AddDefaultValue(
            model_name="testhappypath", name="dob", value=datetime.date(1970, 1, 1)
        ),
        AddDefaultValue(model_name="testhappypath", name="rebirth", value=NOW),
        AddDefaultValue(model_name="testhappypath", name="married", value=TODAY),
    ]
